[package]
edition = "2021"
license = "MIT"
name    = "rspack_cache"
version = "0.1.0"

[dependencies]
rkyv          = { workspace = true, features = ["validation"] }
rspack_macros = { path = "../rspack_macros" }
