[package]
edition = "2021"
license = "MIT"
name    = "rspack_cacheable"
version = "0.1.0"

[dependencies]
inventory     = { workspace = true }
once_cell     = { workspace = true }
rkyv          = { workspace = true, features = ["validation"] }
rspack_macros = { path = "../rspack_macros" }
